export const A_GRAVITY = 9.80665; // Standard acceleration due to gravity (m/s^2)
export const SL_PRESSURE = 101325; // Sea level pessure (Pa)
export const LAPSE_RATE = 0.0065; // Temperature lapse rate (K/m)
export const SL_TEMP = 288.15; // Sea level temperature (K)
export const MM_AIR = 0.0289644; // Molar mass of dry air (kg/mol)
export const GAS_CONST = 8.31447; // Universal gas constant (J/mol/K)
